logging:
  level:
    root: INFO        
    org.springframework:
        security: DEBUG
        web: ERROR         
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'  